from __future__ import annotations

from pathlib import Path


BASE_DIR = Path(__file__).resolve().parent
DATABASE_PATH = BASE_DIR / "sentiment.sqlite3"

DEFAULT_REFRESH_INTERVAL_HOURS = 6
DEFAULT_COVERAGE_LOOKBACK_HOURS = 24
DEFAULT_MIN_WEIGHTED_SIGNAL_COVERAGE = 25.0

SECTOR_ETFS = {
    "technology": "XLK",
    "financial services": "XLF",
    "financial": "XLF",
    "energy": "XLE",
    "healthcare": "XLV",
    "health care": "XLV",
    "consumer defensive": "XLP",
    "consumer staples": "XLP",
    "consumer cyclical": "XLY",
    "consumer discretionary": "XLY",
    "industrials": "XLI",
    "utilities": "XLU",
    "real estate": "XLRE",
    "communication services": "XLC",
    "communications": "XLC",
    "basic materials": "XLB",
    "materials": "XLB",
}

MARKET_CAP_BUCKETS = [
    ("Mega-cap", 200_000_000_000),
    ("Large-cap", 10_000_000_000),
    ("Mid-cap", 2_000_000_000),
    ("Small-cap", 300_000_000),
    ("Micro-cap", 0),
]

SOURCE_WEIGHTS = {
    "reuters": 1.5,
    "bloomberg": 1.5,
    "financial times": 1.4,
    "ft": 1.4,
    "wall street journal": 1.4,
    "wsj": 1.4,
    "cnbc": 1.2,
    "yahoo finance": 1.0,
    "seeking alpha": 0.8,
    "globenewswire": 0.9,
    "globe newswire": 0.9,
    "business wire": 0.9,
    "pr newswire": 0.8,
    "accesswire": 0.7,
    "fierce biotech": 1.0,
    "spacenews": 0.9,
    "space news": 0.9,
    "defense news": 0.9,
    "reddit": 0.5,
}

UNKNOWN_SOURCE_WEIGHT = 0.4
DUPLICATE_SIMILARITY_THRESHOLD = 0.82

POSITIVE_KEYWORDS = [
    "beats expectations",
    "beat expectations",
    "earnings beat",
    "beats estimates",
    "beat estimates",
    "raises guidance",
    "raised guidance",
    "raise prices",
    "raises prices",
    "upgrade",
    "upgraded",
    "price target raised",
    "outperform",
    "buy rating",
    "record revenue",
    "profit growth",
    "margin expansion",
    "approval",
    "approved",
    "contract win",
    "wins contract",
    "contract award",
    "awarded contract",
    "task order",
    "selected by",
    "jaxa win",
    "launch date",
    "successful launch",
    "milestone payment",
    "narrowed losses",
    "breakeven",
    "break-even",
    "expands manufacturing",
    "manufacturing footprint",
    "accelerates production",
    "deal",
    "nears deal",
    "signs deal",
    "partnership",
    "investing in",
    "investment",
    "value play",
    "ascendant",
    "surge",
    "surges",
    "rally",
    "rallies",
    "jumps",
    "beats",
    "strong demand",
    "expansion",
    "rare ai chip value play",
    "acquisition completed",
    "lawsuit dismissed",
    "fends off lawsuit",
    "dismisses complaint",
    "court dismisses",
    "wins lawsuit",
]

NEGATIVE_KEYWORDS = [
    "misses expectations",
    "missed expectations",
    "misses estimates",
    "missed estimates",
    "cuts guidance",
    "cut guidance",
    "downgrade",
    "downgraded",
    "price target cut",
    "sell rating",
    "lawsuit",
    "investigation",
    "sec probe",
    "probe",
    "regulatory risk",
    "profit warning",
    "revenue decline",
    "margin compression",
    "bankruptcy",
    "fraud",
    "debt concern",
    "shares drop",
    "shares fall",
    "shares slide",
    "stock drops",
    "stock falls",
    "plunge",
    "plunges",
    "crash",
    "delays",
    "constant delays",
    "slump",
    "slumps",
    "worst day",
    "concerns",
    "risk",
    "risks",
    "exits",
    "departs",
    "to leave",
    "leaves",
    "departure",
    "departures",
    "leaves for rival",
    "quit",
    "frustration",
    "shortage",
    "price hike",
    "raises prices due to",
    "antitrust",
    "doj",
]

NEUTRAL_KEYWORDS = [
    "announces",
    "says",
    "plans",
    "comments",
    "discusses",
]

DRIVER_KEYWORDS = {
    "revenue": ["revenue", "sales", "top line", "bookings"],
    "costs": ["cost", "costs", "expense", "expenses", "layoff", "layoffs"],
    "margins": ["margin", "margins", "profitability", "gross margin"],
    "demand": ["demand", "orders", "backlog", "traffic", "subscribers", "production", "manufacturing"],
    "regulation": ["regulator", "regulatory", "sec", "fda", "approval", "antitrust"],
    "legal": ["lawsuit", "settlement", "fraud", "court", "probe", "investigation"],
    "management": ["ceo", "cfo", "executive", "management", "resigns", "appointed"],
    "macro": ["inflation", "rates", "recession", "currency", "oil", "macro"],
    "earnings": ["earnings", "eps", "quarter", "guidance", "forecast", "profit warning"],
    "capital allocation": ["dividend", "buyback", "debt", "issuance", "cash flow"],
}

MARKET_MOVING_TERMS = [
    "bankruptcy",
    "fraud",
    "sec probe",
    "cuts guidance",
    "raises guidance",
    "misses expectations",
    "beats expectations",
    "record revenue",
    "acquisition completed",
]

EVENT_TYPE_KEYWORDS = {
    "earnings": ["earnings", "eps", "quarterly results", "profit", "revenue", "losses", "narrowed losses"],
    "guidance": ["raises guidance", "cuts guidance", "guidance", "forecast", "outlook"],
    "analyst_upgrade": ["upgrade", "upgraded", "price target raised", "outperform"],
    "analyst_downgrade": ["downgrade", "downgraded", "price target cut", "underperform"],
    "management_change": ["ceo", "cfo", "resigns", "steps down", "appointed", "management change", "to leave", "leaves", "departs", "departure"],
    "acquisition": ["acquisition", "acquires", "acquired", "takeover"],
    "merger": ["merger", "merge", "combination"],
    "share_buyback": ["buyback", "repurchase", "share repurchase"],
    "dividend": ["dividend", "payout"],
    "product_launch": ["product launch", "launches", "launch date", "new product", "unveils", "deployed", "deploy", "production"],
    "contract_win": ["contract win", "wins contract", "contract award", "awarded contract", "task order", "deal signed", "partnership", "selected by", "jaxa win"],
    "regulation": ["regulator", "regulatory", "fda", "antitrust", "approval"],
    "lawsuit": ["lawsuit", "sued", "court", "settlement"],
    "investigation": ["investigation", "probe", "sec probe"],
    "macro": ["inflation", "interest rates", "recession", "tariff", "currency", "macro"],
    "financing": ["debt", "offering", "financing", "credit facility", "bond"],
    "bankruptcy": ["bankruptcy", "chapter 11", "insolvency"],
}

EVENT_TYPE_PRIORITY = [
    "bankruptcy",
    "investigation",
    "lawsuit",
    "guidance",
    "earnings",
    "analyst_downgrade",
    "analyst_upgrade",
    "acquisition",
    "merger",
    "management_change",
    "share_buyback",
    "dividend",
    "contract_win",
    "regulation",
    "financing",
    "product_launch",
    "macro",
]

EVENT_SIGNAL_PRIORS = {
    "bankruptcy": {
        "direction": "bearish",
        "score": 4.0,
        "materiality_floor": 9,
        "note": "bankruptcy is usually market-moving and equity-negative",
    },
    "investigation": {
        "direction": "bearish",
        "score": 2.6,
        "materiality_floor": 7,
        "note": "formal investigations create legal and regulatory overhang",
    },
    "lawsuit": {
        "direction": "bearish",
        "score": 1.8,
        "materiality_floor": 5,
        "note": "lawsuits are usually negative unless explicitly dismissed or settled favorably",
    },
    "guidance": {
        "direction": "surprise",
        "score": 2.8,
        "materiality_floor": 7,
        "note": "guidance changes directly update forward expectations",
    },
    "earnings": {
        "direction": "surprise",
        "score": 1.8,
        "materiality_floor": 6,
        "note": "earnings matter most when they beat or miss expectations",
    },
    "analyst_upgrade": {
        "direction": "bullish",
        "score": 1.8,
        "materiality_floor": 4,
        "note": "analyst upgrades can affect short-term positioning",
    },
    "analyst_downgrade": {
        "direction": "bearish",
        "score": 1.8,
        "materiality_floor": 4,
        "note": "analyst downgrades can affect short-term positioning",
    },
    "share_buyback": {
        "direction": "bullish",
        "score": 1.6,
        "materiality_floor": 5,
        "note": "buybacks are usually supportive when not debt-stressed",
    },
    "dividend": {
        "direction": "bullish",
        "score": 1.2,
        "materiality_floor": 4,
        "note": "dividend increases can signal capital return strength",
    },
    "contract_win": {
        "direction": "bullish",
        "score": 1.8,
        "materiality_floor": 5,
        "note": "contract wins can support revenue visibility",
    },
    "financing": {
        "direction": "bearish",
        "score": 1.2,
        "materiality_floor": 4,
        "note": "financing can imply dilution, debt needs, or balance-sheet pressure",
    },
}

SURPRISE_MULTIPLIERS = {
    "strongly_positive": 1.5,
    "positive": 1.2,
    "neutral": 1.0,
    "negative": 1.2,
    "strongly_negative": 1.5,
}

TICKER_ALIASES = {
    "AAPL": ["apple"],
    "MSFT": ["microsoft"],
    "GOOG": ["google", "alphabet"],
    "GOOGL": ["google", "alphabet"],
    "GOOGLE": ["google", "alphabet"],
    "AMZN": ["amazon"],
    "META": ["meta", "facebook"],
    "NVDA": ["nvidia"],
    "TSLA": ["tesla"],
    "QCOM": ["qualcomm"],
    "AMD": ["advanced micro devices", "amd"],
    "INTC": ["intel"],
    "NFLX": ["netflix"],
    "CRM": ["salesforce"],
    "ORCL": ["oracle"],
    "IBM": ["ibm"],
    "RXRX": ["recursion", "recursion pharmaceuticals"],
    "CRSP": ["crispr therapeutics"],
    "BEAM": ["beam therapeutics"],
    "ARCT": ["arcturus therapeutics"],
    "EDIT": ["editas medicine"],
    "SANA": ["sana biotechnology"],
    "CLLS": ["cellectis"],
    "SOUN": ["soundhound", "soundhound ai"],
    "BBAI": ["bigbear.ai", "bigbear ai"],
    "AI": ["c3.ai", "c3 ai"],
    "EXFY": ["expensify"],
    "OLO": ["olo"],
    "GTLB": ["gitlab"],
    "RKLB": ["rocket lab"],
    "ASTS": ["ast spacemobile"],
    "RDW": ["redwire"],
    "BKSY": ["blacksky"],
    "UEC": ["uranium energy"],
    "UUUU": ["energy fuels"],
    "DNN": ["denison mines"],
    "NXE": ["nexgen energy"],
    "LOVE": ["lovesac"],
    "WRBY": ["warby parker"],
    "TDUP": ["thredup", "thred up"],
    "BARK": ["bark"],
    "JOBY": ["joby aviation"],
    "ACHR": ["archer aviation"],
    "PL": ["planet labs"],
    "IONQ": ["ionq"],
    "RGTI": ["rigetti"],
    "QBTS": ["d-wave quantum", "d wave quantum"],
}

YFINANCE_TICKER_ALIASES = {
    "GOOGLE": "GOOG",
}

COMPANY_NAME_BY_TICKER = {
    "RXRX": "Recursion Pharmaceuticals",
    "CRSP": "CRISPR Therapeutics",
    "SANA": "Sana Biotechnology",
    "BEAM": "Beam Therapeutics",
    "EDIT": "Editas Medicine",
    "ARCT": "Arcturus Therapeutics",
    "CLLS": "Cellectis",
    "SOUN": "SoundHound AI",
    "BBAI": "BigBear.ai",
    "AI": "C3.ai",
    "EXFY": "Expensify",
    "OLO": "Olo",
    "GTLB": "GitLab",
    "RKLB": "Rocket Lab",
    "ASTS": "AST SpaceMobile",
    "RDW": "Redwire",
    "BKSY": "BlackSky",
    "UEC": "Uranium Energy",
    "UUUU": "Energy Fuels",
    "DNN": "Denison Mines",
    "NXE": "NexGen Energy",
    "LOVE": "Lovesac",
    "WRBY": "Warby Parker",
    "TDUP": "ThredUp",
    "BARK": "BARK",
    "JOBY": "Joby Aviation",
    "ACHR": "Archer Aviation",
    "PL": "Planet Labs",
    "IONQ": "IonQ",
    "RGTI": "Rigetti Computing",
    "QBTS": "D-Wave Quantum",
}

STARTER_UNIVERSE_25 = [
    "RXRX",
    "CRSP",
    "BEAM",
    "ARCT",
    "EDIT",
    "SOUN",
    "BBAI",
    "AI",
    "EXFY",
    "GTLB",
    "RKLB",
    "ASTS",
    "RDW",
    "BKSY",
    "UEC",
    "UUUU",
    "DNN",
    "NXE",
    "LOVE",
    "WRBY",
    "TDUP",
    "BARK",
    "JOBY",
    "IONQ",
    "RGTI",
]

STARTER_UNIVERSE_10 = [
    "RXRX",
    "RKLB",
    "ASTS",
    "SOUN",
    "BBAI",
    "UUUU",
    "CRSP",
    "ARCT",
    "RDW",
    "IONQ",
]

SMALL_CAP_RESEARCH_UNIVERSE = [
    "CRSP",
    "RXRX",
    "SANA",
    "BEAM",
    "EDIT",
    "ARCT",
    "CLLS",
    "SOUN",
    "BBAI",
    "AI",
    "EXFY",
    "OLO",
    "GTLB",
    "RKLB",
    "ASTS",
    "RDW",
    "BKSY",
    "UEC",
    "UUUU",
    "DNN",
    "NXE",
    "LOVE",
    "WRBY",
    "TDUP",
    "BARK",
    "JOBY",
    "ACHR",
    "PL",
    "IONQ",
    "RGTI",
    "QBTS",
]

TICKER_UNIVERSES = {
    "starter25": STARTER_UNIVERSE_25,
    "starter10": STARTER_UNIVERSE_10,
    "smallcap": SMALL_CAP_RESEARCH_UNIVERSE,
}

MARKET_REACTION_POSITIVE = [
    "shares rise",
    "shares rose",
    "shares jump",
    "shares jumped",
    "shares rally",
    "shares rallied",
    "stock rises",
    "stock rose",
    "stock jumps",
    "stock jumped",
    "stock rallies",
    "stock rallied",
    "premarket gain",
    "after-hours gain",
    "trades higher",
    "moves higher",
    "surges",
    "soars",
]

MARKET_REACTION_NEGATIVE = [
    "shares fall",
    "shares fell",
    "shares drop",
    "shares dropped",
    "shares slide",
    "shares slid",
    "stock falls",
    "stock fell",
    "stock drops",
    "stock dropped",
    "stock slides",
    "selloff",
    "sell-off",
    "worst day",
    "premarket drop",
    "after-hours drop",
    "trades lower",
    "moves lower",
    "plunges",
    "tumbles",
]

UNCERTAINTY_TERMS = [
    "reportedly",
    "nears",
    "in talks",
    "explores",
    "could",
    "may",
    "plans",
    "rumored",
    "potential",
    "considering",
]

CONTRADICTION_TERMS = [" but ", " however ", " although ", " despite ", " even as ", " while "]

RELEVANCE_WEIGHTS = {
    "direct": 1.0,
    "related": 0.7,
    "sector": 0.4,
    "low": 0.2,
    "irrelevant": 0.0,
}

NEWS_FEED_PRESETS = [
    {
        "name": "Yahoo Finance",
        "source": "Yahoo Finance",
        "url_template": "https://feeds.finance.yahoo.com/rss/2.0/headline?s={ticker}&region=US&lang=en-US",
        "ticker_specific": True,
    },
    {
        "name": "Reuters via Google News",
        "source": "Reuters",
        "url_template": "https://news.google.com/rss/search?q=site%3Areuters.com%20{ticker}&hl=en-US&gl=US&ceid=US%3Aen",
        "ticker_specific": True,
    },
    {
        "name": "CNBC via Google News",
        "source": "CNBC",
        "url_template": "https://news.google.com/rss/search?q=site%3Acnbc.com%20{ticker}&hl=en-US&gl=US&ceid=US%3Aen",
        "ticker_specific": True,
    },
    {
        "name": "GlobeNewswire via Google News",
        "source": "GlobeNewswire",
        "url_template": "https://news.google.com/rss/search?q=site%3Aglobenewswire.com%20%28%22{company}%22%20OR%20%22%24{ticker}%22%20OR%20%22{ticker}%20stock%22%29&hl=en-US&gl=US&ceid=US%3Aen",
        "ticker_specific": True,
    },
    {
        "name": "Business Wire via Google News",
        "source": "Business Wire",
        "url_template": "https://news.google.com/rss/search?q=site%3Abusinesswire.com%20%28%22{company}%22%20OR%20%22%24{ticker}%22%20OR%20%22{ticker}%20stock%22%29&hl=en-US&gl=US&ceid=US%3Aen",
        "ticker_specific": True,
    },
    {
        "name": "PR Newswire via Google News",
        "source": "PR Newswire",
        "url_template": "https://news.google.com/rss/search?q=site%3Aprnewswire.com%20%28%22{company}%22%20OR%20%22%24{ticker}%22%20OR%20%22{ticker}%20stock%22%29&hl=en-US&gl=US&ceid=US%3Aen",
        "ticker_specific": True,
    },
    {
        "name": "Accesswire via Google News",
        "source": "Accesswire",
        "url_template": "https://news.google.com/rss/search?q=site%3Aaccesswire.com%20%28%22{company}%22%20OR%20%22%24{ticker}%22%20OR%20%22{ticker}%20stock%22%29&hl=en-US&gl=US&ceid=US%3Aen",
        "ticker_specific": True,
    },
    {
        "name": "Seeking Alpha via Google News",
        "source": "Seeking Alpha",
        "url_template": "https://news.google.com/rss/search?q=site%3Aseekingalpha.com%20{ticker}&hl=en-US&gl=US&ceid=US%3Aen",
        "ticker_specific": True,
    },
    {
        "name": "Bloomberg via Google News",
        "source": "Bloomberg",
        "url_template": "https://news.google.com/rss/search?q=site%3Abloomberg.com%20{ticker}&hl=en-US&gl=US&ceid=US%3Aen",
        "ticker_specific": True,
    },
    {
        "name": "Financial Times via Google News",
        "source": "Financial Times",
        "url_template": "https://news.google.com/rss/search?q=site%3Aft.com%20{ticker}&hl=en-US&gl=US&ceid=US%3Aen",
        "ticker_specific": True,
    },
    {
        "name": "Wall Street Journal via Google News",
        "source": "Wall Street Journal",
        "url_template": "https://news.google.com/rss/search?q=site%3Awsj.com%20{ticker}&hl=en-US&gl=US&ceid=US%3Aen",
        "ticker_specific": True,
    },
    {
        "name": "Fierce Biotech via Google News",
        "source": "Fierce Biotech",
        "url_template": "https://news.google.com/rss/search?q=site%3Afiercebiotech.com%20%28%22{company}%22%20OR%20%22%24{ticker}%22%20OR%20%22{ticker}%20stock%22%29&hl=en-US&gl=US&ceid=US%3Aen",
        "ticker_specific": True,
    },
    {
        "name": "SpaceNews via Google News",
        "source": "SpaceNews",
        "url_template": "https://news.google.com/rss/search?q=site%3Aspacenews.com%20%28%22{company}%22%20OR%20%22%24{ticker}%22%20OR%20%22{ticker}%20stock%22%29&hl=en-US&gl=US&ceid=US%3Aen",
        "ticker_specific": True,
    },
    {
        "name": "Defense News via Google News",
        "source": "Defense News",
        "url_template": "https://news.google.com/rss/search?q=site%3Adefensenews.com%20%28%22{company}%22%20OR%20%22%24{ticker}%22%20OR%20%22{ticker}%20stock%22%29&hl=en-US&gl=US&ceid=US%3Aen",
        "ticker_specific": True,
    },
    {
        "name": "Reddit r/stocks search",
        "source": "Reddit",
        "url_template": "https://www.reddit.com/r/stocks/search.rss?q={ticker}&restrict_sr=1&sort=new",
        "ticker_specific": True,
    },
    {
        "name": "CNBC Finance",
        "source": "CNBC",
        "url_template": "https://www.cnbc.com/id/10000664/device/rss/rss.html",
        "ticker_specific": False,
    },
    {
        "name": "CNBC Business",
        "source": "CNBC",
        "url_template": "https://www.cnbc.com/id/10001147/device/rss/rss.html",
        "ticker_specific": False,
    },
    {
        "name": "Seeking Alpha Breaking News",
        "source": "Seeking Alpha",
        "url_template": "https://seekingalpha.com/market_currents.xml",
        "ticker_specific": False,
    },
]
